print("Welcome to the Band Name Generator.")
city = str(input("What's the name of the city you grew up in? \n"))
print(city)
pet = str(input("What's your pet's name? \n"))
print(pet)
print("Your band name could be " + city + " " + pet)
